#!/bin/bash
# QUICK START GUIDE - PhotoShare Deployment

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         PhotoShare - Azure Deployment Quick Start             ║"
echo "╚════════════════════════════════════════════════════════════════╝"

echo ""
echo "✅ ALREADY CONFIGURED:"
echo "   • Azure App Service: scalable-photo-app"
echo "   • SQL Database: scalable-db"
echo "   • Storage Account: scalablemediastorage"
echo "   • Region: France Central"
echo ""

echo "📋 YOUR TODO LIST:"
echo ""
echo "1️⃣  CREATE GITHUB REPOSITORY"
echo "   $ cd \"Scalable - Benjamin\""
echo "   $ git remote add origin https://github.com/lnrtotal-ux/scalable-photo.git"
echo "   $ git branch -M main"
echo "   $ git add ."
echo "   $ git commit -m \"initial commit\""
echo "   $ git push -u origin main"
echo ""

echo "2️⃣  ADD GITHUB SECRETS"
echo "   Get publish profile:"
echo "   $ az webapp deployment list-publishing-profiles \\"
echo "     --resource-group scalable-group --name scalable-photo-app --xml"
echo ""
echo "   Get storage key:"
echo "   $ az storage account keys list \\"
echo "     --resource-group scalable-group --account-name scalablemediastorage \\"
echo "     --query '[0].value' -o tsv"
echo ""
echo "   Add to GitHub Settings → Secrets:"
echo "   • AZURE_WEBAPP_PUBLISH_PROFILE = (paste XML)"
echo "   • AZURE_STORAGE_ACCOUNT_KEY = (paste key)"
echo ""

echo "3️⃣  INITIALIZE DATABASE"
echo "   Azure Portal → SQL Databases → scalable-db → Query Editor"
echo "   Run the SQL from GITHUB_SETUP.md (Part 3)"
echo ""

echo "4️⃣  DEPLOY"
echo "   $ git push origin main"
echo "   Monitor: GitHub Actions → Deploy PhotoShare to Azure"
echo ""

echo "🌐 YOUR URLS:"
echo "   Frontend: https://scalable-photo-app.azurewebsites.net"
echo "   API:      https://scalable-photo-app.azurewebsites.net/api"
echo "   Health:   https://scalable-photo-app.azurewebsites.net/health"
echo ""

echo "👤 DEMO ACCOUNTS:"
echo "   Admin: admin / Admin123!"
echo "   Creator: john_creator / Creator123!"
echo "   User: jane_user / User123!"
echo ""

echo "📚 DOCUMENTATION:"
echo "   • GITHUB_SETUP.md - Complete GitHub deployment guide"
echo "   • AZURE_SETUP_COMPLETE.md - What's been set up"
echo "   • README.md - Project overview"
echo ""

echo "💡 TIP: After every push to main, GitHub automatically deploys!"
echo ""
